name: deploy-and-run
on: 
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .ssh dir
        run: mkdir ~/.ssh
      - name: Create known hosts file
        run: touch ~/.ssh/known_hosts
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy with rsync
        run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/nosdave/nosdave-frontend/
      - name: Run extractor and parsing tool
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ~/nosdave-frontend; npm install; npm run build; pm2 start"